### ISSUE TITLE
Latest version of docker:stable-dind not working with command: --insecure-registry=example.domain

### ISSUE THREAD

**Issue by massimeddu** [docker-library/docker#130]
Hi,

I have an issue with the latest docker:stable-dind and docker:git. I'm using them in gitlab-ci pipeline.

Following version is not working:

  image: docker:stable-git
  services:
  - name: docker:stable-dind
    command: ["--insecure-registry=example.domain:4567"]

Returning this error:

ERROR: Preparation failed: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? (executor_docker.go:1150:0s)

Following version is working well:

  image: docker:18.06.0-git
  services:
  - name: docker:18.06.0-dind
    command: ["--insecure-registry=example.domain:4567"]

Can you help me?

Thank you.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by akkie** [comment]
@wglambert We have this issue as well with the actual `docker:dind` image. Switching to `docker:18.09.7-dind` fixes the issue:

Our GitLab job looks like:

```yaml
publish release image:
  image: docker:stable
  stage: publish
  services:
    - name: docker:dind
      command: [ "--insecure-registry=registry.domain.local" ]
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.domain.local
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg "SONAR_LOGIN=$SONAR_LOGIN" .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
```

The issue is that the docker login will not work because of the self signed SSL cert.
```
$ echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.domain.local
time="2019-07-23T13:34:50Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://registry.domain.local/v2/: x509: certificate signed by unknown authority"
Get https://registry.domain.local/v2/: x509: certificate signed by unknown authority
```

I don't think that this is a GitLab issue, because switching to an older image works as expected.
