### ISSUE TITLE
How can I address an out container from an inner container?

### ISSUE THREAD

**Issue by bergtwvd** [docker-library/docker#133]
This continues the example provided in https://github.com/docker-library/docker/issues/132. How can I address an outer container from an inner container?

Example:
````
version: '3'

services:

 dind:
  image: docker:18.06-dind
  privileged: true
  container_name: docker1

 client:
  image: docker:18.06-dind
  container_name: docker2
  command:
  - /bin/sh
  - -c
  - |
    sleep 1;
    docker run -d --name test busybox sleep 3600;
    docker logs -f test
  environment:
  - DOCKER_HOST=dind
  depends_on:
  - dind
````

For example:
````
$ docker exec docker1 docker exec test ping docker1
ping: bad address 'docker1'
````

Obviously I need to pass in the DNS server for the outer container network with the ``--dns`` option, but what address can I provide for the DNS server?
