### ISSUE TITLE
git clone via ssh blocked when build image with dind

### ISSUE THREAD

**Issue by ityoung** [docker-library/docker#137]
I use docker:dind in gitlab-ci, and set ssh private key before git clone. Before `git clone` really start, the console on gitlab shows "Warning: Permanently added the ECDSA host key for IP address '<MY_GIT_IP>' to the list of known hosts.", and stay block until timeout.

There is part of my script:

**.gitlab-ci.yml:**

```
build:
  stage: build
  image: docker:git
  variables:
    GIT_STRATEGY: fetch
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  script:
    # the variable SSH_PRIVATE_KEY was set on gitlab>setting>CI/CD>Variables, the value is a key that have access right to my gitlab repositry.
    - docker build --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" -t server:ci .
```

**Dockerfile:**

```
FROM python:3.5-stretch

ARG SSH_PRIVATE_KEY

RUN mkdir /root/.ssh/ \
  && echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa \
  && chmod -R 600 /root/.ssh/ \
  && touch /root/.ssh/known_hosts \
  && ssh-keyscan <MY_GIT_DOMAIN> >> /root/.ssh/known_hosts \
  && git clone git@<MY_GIT_DOMAIN>:backend/<MY_GIT_PROJECT>.git
```

In my another project, the dind works perfectly without SSH connection to my gitlab, and also, the Dockerfile above works well on my PC without dind, so I think is there anything I missed, such as limit about network layer?
