### ISSUE TITLE
Docker and Docker-dind :  Unable to pip install related to #112

### ISSUE THREAD

**Issue by Zauxst** [docker-library/docker#139]
Hello,

My issue is related to #112;
I have a kubernetes stack which I'm trying to run docker-dind and docker-git.
```yaml
yaml:
apiVersion: v1
kind: Pod
metadata:
 name: dind
spec:
 containers:
 - name: builder
   image: docker:18.06.1-git
   imagePullPolicy: Always
   command: ['cat']
   tty: true
   env:
   - name: DOCKER_HOST
     value: tcp://localhost:2375
 - name: dind
   image: docker:18.06.1-dind
   securityContext:
     privileged: true
   volumeMounts:
   - name: dind-storage
     mountPath: /var/lib/docker
 volumes:
 - name: dind-storage
   emptyDir: {}
```
It fails when doing pip3 install --upgrade pip3.

If I manually apply the fix from #112 after a while the command starts working.

I'd like to avoid to package my own DIND container and I'm trying to work with the entrypoint.sh if possible to apply `apk add --no-cache libressl` at startup.
