### ISSUE TITLE
volumes  Error

### ISSUE THREAD

**Issue by zhangxiangfeng** [docker-library/docker#196]
```
simon@simon-jian24:/data/jian24-deploy$ docker exec -it openresty-1.15.8.2 nginx -t
nginx: [emerg] open() "/usr/local/openresty/nginx/conf/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed

```
but  
```
simon@simon-jian24:/data/jian24-deploy$  docker exec -it openresty-1.15.8.2 /bin/bash
root@710f59d942c2:/# cd /usr/local/openresty/nginx/conf/ 
root@710f59d942c2:/usr/local/openresty/nginx/conf# ls -alh
ls: cannot access 'nginx.conf': No such file or directory
total 72K
drwxr-xr-x 1 root root 4.0K Oct 21 06:24 .
drwxr-xr-x 1 root root 4.0K Oct 24 11:42 ..
-rw-r--r-- 1 root root 1.1K Aug 30 07:49 fastcgi.conf
-rw-r--r-- 1 root root 1.1K Aug 30 07:49 fastcgi.conf.default
-rw-r--r-- 1 root root 1007 Aug 30 07:49 fastcgi_params
-rw-r--r-- 1 root root 1007 Aug 30 07:49 fastcgi_params.default
-rw-r--r-- 1 root root 2.8K Aug 30 07:49 koi-utf
-rw-r--r-- 1 root root 2.2K Aug 30 07:49 koi-win
-rw-r--r-- 1 root root 5.2K Aug 30 07:49 mime.types
-rw-r--r-- 1 root root 5.2K Aug 30 07:49 mime.types.default
-????????? ? ?    ?       ?            ? nginx.conf
-rw-r--r-- 1 root root 2.6K Aug 30 07:49 nginx.conf.default
-rw-r--r-- 1 root root  636 Aug 30 07:49 scgi_params
-rw-r--r-- 1 root root  636 Aug 30 07:49 scgi_params.default
-rw-r--r-- 1 root root  664 Aug 30 07:49 uwsgi_params
-rw-r--r-- 1 root root  664 Aug 30 07:49 uwsgi_params.default
-rw-r--r-- 1 root root 3.6K Aug 30 07:49 win-utf
```
--------
```
version: '3.1'
services:
  openresty:
    container_name: openresty-1.15.8.2
    image: openresty/openresty
    restart: always
    ports:
      - 8057:80
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/jian24-deploy/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
```

```
root@710f59d942c2://# ls -alh  /etc/openresty
lrwxrwxrwx 1 root root 31 Aug 30 07:49 /etc/openresty -> /usr/local/openresty/nginx/conf
```
---------
i edit  /data/jian24-deploy/openresty/nginx.conf
and error !!!!
