### ISSUE TITLE
dockerd-entrypoint.sh in dind should allow listener interface to be overridden

### ISSUE THREAD

**Issue by GrahamDumpleton** [docker-library/docker#227]
In the ``dockerd-entrypoint.sh`` script of the ``dind`` images, the docker daemon listens on all interfaces by using ``--host=tcp://0.0.0.0:2376`` and ``--host=tcp://0.0.0.0:2375``. This means that the docker daemon is always accessible outside of the host it is notionally running in, which may be undesirable from a security perspective.

There should be a means to override the listener interface using an environment variable so that ``0.0.0.0`` can be replaced with ``127.0.0.1`` if required.

The need for this comes up when using ``dind`` images as side car container inside of a pod in Kubernetes. You may not ever want the docker daemon visible outside of the pod. Thus it is desirable to be able to override the listener interface so that ``127.0.0.1`` is used, ensuring the docker daemon is only accessible to other containers running in the same pod.

Right now to ensure this one has to override the container command and edit the ``dockerd-entrypoint.sh`` script before executing it.

```
      - name: docker
        image: docker:dind
        command:
        - /bin/sh
        - -c
        - "sed -i.bak 's/0.0.0.0/127.0.0.1/g' /usr/local/bin/dockerd-entrypoint.sh && dockerd-entrypoint.sh"
        securityContext:
          privileged: true
```

An ability to do this using an environment variable would be preferable.

Although in this example Kubernetes was used, one may want to do this when executing in standard docker system direct on a host as well.

cc @jorgemoralespou
