### ISSUE TITLE
Docker login during CI doesn't work with docker:19.03.8 (docker:19.03.8-dind as service)

### ISSUE THREAD

**Issue by flavioarieta** [docker-library/docker#259]
Hi,

I've been using the same pipeline to build and push docker images for almost a year without any problems, but lately I'm getting the following error:
```
$ docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password

Authenticating with credentials from /root/.docker/config.json
ERROR: Job failed: exit code 1
```

Both `CI_REGISTRY_USER` and `CI_REGISTRY_PASSWORD` haven't changed, so I thought that the password, which is an access token, had expired. I tried creating a new token and even using my personal password, but everything I tried resulted in the same error. The `CI_REGISTRY_USER` is a variable holding just the userid of the account, not the email. 

To verify I tried the same docker login command on my notebook and it logged in without a problem.

Just in case I'm adding the stage of gitlab-ci.yml related to this:
```
release_docker_image_qa:
  image: docker:19.03.8
  stage: release_docker_image_qa
  when: manual
  services:
    - name: docker:19.03.8-dind
  script:
    - mv erp-*.jar ./docker/
    - cd docker
    - ls -lah
    - docker info
    - sed -i "s/__CONF_BRANCH__/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}/" Dockerfile
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - echo "$A_CONF" > conf
    - echo "$A_CRED" > cred
    - docker build -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_USER}/${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}-qa"
    - docker push "${CI_REGISTRY_USER}/${CI_REGISTRY_IMAGE}:${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}-${CI_COMMIT_SHORT_SHA}-qa"
  only:
    - merge_requests
```

Did someone already had this problem or have a guess on what I'am missing?
Thanks
