### ISSUE TITLE
Docker login during CI doesnt work when use docker:19.03.14 from own registry

### ISSUE THREAD

**Issue by itkg-ppottie** [docker-library/docker#283]
With quota limit to download images on Docker hub, i want to use a copy on my own registry.
Same image , no modified, but when i try the login failed in CI 

with this CI : it's work
```
.template-dind: &template-dind
  image: docker/compose:alpine-1.27.4
  services:
    - name:  docker:19.03.14-dind
      entrypoint:  ['dockerd-entrypoint.sh']
      alias: docker
      command: ["--insecure-registry", "XXXXXX:8443"]
```
with this service , it's failed:
```
 .template-dind: &template-dind
  image: docker/compose:alpine-1.27.4
  services:
    - name:  XXXXXX:8443/common/docker/test/docker:19.03.14-dind
      entrypoint:  ['dockerd-entrypoint.sh']
      alias: docker
      command: ["--insecure-registry", "XXXXXX:8443"]

```
The error:
```
 $ docker login $CI_REGISTRY -u gitlab-ci-token -p $REGISTRY_TOKEN
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
time="2020-12-22T16:02:13Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://XXXXXX:8443/v2/: x509: certificate signed by unknown authority"
Get XXXXXX:8443/v2/: x509: certificate signed by unknown authority

Cleaning up file based variables

118ERROR: Job failed: exit code 1
```
gitlab-runner 13.4.1
base image: docker/compose:alpine-1.27.4

i'm lost, any help?

**Comment by wglambert** [comment]
https://docs.docker.com/registry/insecure/

For using `--insecure-registry` I think you have to use port 5000

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by tao12345666333** [comment]
Can you provide a more detailed .gitlab-ci.yml file?
Also, where is your `docker login` operation?

You can try this:

```
 .template-dind: &template-dind
  image: docker/compose:alpine-1.27.4
  services:
      - name:  XXXXXX:8443/common/docker/test/docker:19.03.14-dind
      alias: docker
      command: ["--insecure-registry=https://XXXXXX:8443"]
```
