### ISSUE TITLE
dind-rootless fails

### ISSUE THREAD

**Issue by mo-saeed** [docker-library/docker#296]
Hello,

Am trying to run dind-rootless image but the container fails with this error

```
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 117 [0 1000 1 1 100000 65536] failed: newuidmap: write to uid_map failed: Operation not permitted
```

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

**Comment by mo-saeed** [comment]
Hi @wglambert I am using kubernetes, so preparing a deployment file like that with this [image](https://hub.docker.com/layers/docker/library/docker/dind-rootless/images/sha256-9ad12bb649463b45bb39481eba38b2f5c5cfe8471e571917329ee0c19171a71d?context=explore) but the pod keep restarting throwing the above error
kubernetes: EKS 1.19.6

**Comment by mo-saeed** [comment]
Here's the full log from the pod:

```
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................................................................................++++
....................................++++
e is 65537 (0x010001)
Generating RSA private key, 4096 bit long modulus (2 primes)
................................................................................................................................................++++
........................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind server
Getting CA Private Key
/certs/server/cert.pem: OK
Generating RSA private key, 4096 bit long modulus (2 primes)
...............................................................................................++++
........................................++++
e is 65537 (0x010001)
Signature ok
subject=CN = docker:dind client
Getting CA Private Key
/certs/client/cert.pem: OK
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 50 [0 1000 1 1 100000 65536] failed: newuidmap: write to uid_map failed: Operation not permitted
: exit status 1
```

**Comment by mo-saeed** [comment]
Here's also the simple pod
```
apiVersion: v1
kind: Pod
metadata:
  name: test-dind-rootless
  labels:
    role: myrole
spec:
  containers:
    - name: dind-rootless
      image: docker:dind-rootless
~
```

**Comment by wglambert** [comment]
https://github.com/docker-library/docker/issues/291#issuecomment-771013612

You still need `--privileged` https://github.com/docker-library/docker/issues/151#issuecomment-483185972

You'll also want the `command` set to `--experimental` for `dockerd`https://github.com/docker-library/docker/issues/281#issuecomment-744766015

**Comment by mo-saeed** [comment]
Thanks @wglambert now it runs but I can't run for example `docker ps` with this error ```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: dial unix /var/run/docker.sock: connect: permission denied```

**Comment by wglambert** [comment]
Ah yeah, you'll also want to specify a couple environment variables. Here's a working `pod.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-dind-rootless
  labels:
    role: myrole
spec:
  containers:
    - name: dind-rootless
      image: docker:dind-rootless
      securityContext:
        privileged: true
      env:
      - name: DOCKER_TLS_CERTDIR
        value: "/certs"
      - name: DOCKER_HOST
        value: "unix:///run/user/1000/docker.sock"
```

```console
$ kubectl apply -f pod.yaml
pod/test-dind-rootless created

$ kubectl exec -it test-dind-rootless -- ash
/ $ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

/ $ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
5d3b2c2d21bb: Pull complete
3fc2062ea667: Pull complete
75adf526d75b: Pull complete
Digest: sha256:b4f9e18267eb98998f6130342baacaeb9553f136142d40959a1b46d6401f0f2b
Status: Downloaded newer image for ubuntu:latest
docker.io/library/ubuntu:latest
```
