### ISSUE TITLE
Issue: Server did not provide an image ID. Cannot write /tmp/tmp9lwj8z_v

### ISSUE THREAD

**Issue by srikavya-kola** [docker-library/docker#304]
I'm running Jenkins as a docker container in kubernetes so I had to use DinD(docker-in-docker container) as a sidecar for Jenkins using helm chart to build docker images. Docker build works perfectly fine, but when I started using docker-compose I see this issue consistently.

**docker-compose.yaml:**

```
version: "3.4" # docker-compose version
x-volumes: &volumes 
  - ./.aws:/root/.aws 
  - .:/app  
services:
  ci: 
    build: 
    context: . 
    dockerfile: Dockerfile
    volumes: *volumes
    tty: false 
    command: ["npm", "test"]
```

**Jenkins_helmchart_values.yaml:**

```
controller:
  containerEnv:
      - name: DOCKER_HOST 
        value: tcp://localhost:2375 
sidecars:
    other:
    - name: dind-daemon 
      image: docker:1.12.6-dind 
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 256Mi
      securityContext: 
        privileged: true 
      volumeMounts: 
      - name: docker-graph-storage
        mountPath: /var/lib/docker 
```
**Build Log**

```
+ docker-compose up --no-color ci
Creating network "roduct_team_pr_validations_pr-17_default" with the default driver
Building ci
Sending build context to Docker daemon  269.8kB
Step 1 : FROM nikolaik/python-nodejs:python3.7-nodejs12
python3.7-nodejs12: Pulling from nikolaik/python-nodejs
0ecb575e629c: Pulling fs layer
7467d1831b69: Pulling fs layer
feab2c490a3c: Pulling fs layer
f15a0f46f8c3: Pulling fs layer
937782447ff6: Pulling fs layer
e78b7aaaab2c: Pulling fs layer
d6bffa7c00e3: Pulling fs layer
20e485dc4919: Pulling fs layer
d691069cb281: Pulling fs layer
a5b756fa5cc9: Pulling fs layer
937782447ff6: Waiting
e78b7aaaab2c: Waiting
d6bffa7c00e3: Waiting
20e485dc4919: Waiting
d691069cb281: Waiting
a5b756fa5cc9: Waiting
f15a0f46f8c3: Waiting
7467d1831b69: Verifying Checksum
7467d1831b69: Download complete
feab2c490a3c: Verifying Checksum
feab2c490a3c: Download complete
0ecb575e629c: Verifying Checksum
0ecb575e629c: Download complete
f15a0f46f8c3: Verifying Checksum
f15a0f46f8c3: Download complete
e78b7aaaab2c: Verifying Checksum
e78b7aaaab2c: Download complete
20e485dc4919: Verifying Checksum
20e485dc4919: Download complete
d691069cb281: Verifying Checksum
d691069cb281: Download complete
d6bffa7c00e3: Verifying Checksum
d6bffa7c00e3: Download complete
a5b756fa5cc9: Verifying Checksum
a5b756fa5cc9: Download complete
937782447ff6: Verifying Checksum
937782447ff6: Download complete
0ecb575e629c: Pull complete
7467d1831b69: Pull complete
feab2c490a3c: Pull complete
f15a0f46f8c3: Pull complete
937782447ff6: Pull complete
e78b7aaaab2c: Pull complete
d6bffa7c00e3: Pull complete
20e485dc4919: Pull complete
d691069cb281: Pull complete
a5b756fa5cc9: Pull complete
Digest: sha256:f6205d7554cacc7275df386d87f76cb73f77d599b483b6908bc0e01aee834801
Status: Downloaded newer image for nikolaik/python-nodejs:python3.7-nodejs12
 ---> 3a11a11490a6
Step 2 : WORKDIR /app
 ---> Running in 9afbaec3cfe1
 ---> f1eca4ba6e1f
Removing intermediate container 9afbaec3cfe1
Step 3 : COPY package.json .
 ---> e79d3034b149
Removing intermediate container bf93ca989f13
Step 4 : COPY . .
 ---> 4d79cc473996
Removing intermediate container 871b1cff3a31
Step 5 : CMD echo Hello World!
 ---> Running in 2640e2d2d71c
 ---> f1a654cc9f06
Removing intermediate container 2640e2d2d71c
Successfully built f1a654cc9f06
Server did not provide an image ID. Cannot write /tmp/tmp9lwj8z_v
Service 'ci' failed to build
```
Please let me know if you think anything causing issue here.
