### ISSUE TITLE
[Feature Request] Add a env for add trusted domains for TLS

### ISSUE THREAD

**Issue by mapleeit** [docker-library/docker#312]
I saw there is several default logics here.

https://github.com/docker-library/docker/blob/master/20.10/dind/dockerd-entrypoint.sh#L8

But my use case is here:

```yaml
version: "3.9"
services:
    controller:
        build: .
        ports:
            - 3001:3000
        volumes:
            - cert-volume:/certs
    dind:
        image: docker:20-dind
        privileged: true
        environment: 
            DOCKER_TLS_CERTDIR: /certs
        volumes: 
            - cert-volume:/certs

volumes: 
    cert-volume:
```

I want to use `docker --tlsverify -H=tcp://dind:2376 --tlscacert=/certs/ca/cert.pem --tlscert=/certs/client/cert.pem --tlskey=/certs/client/key.pem version` in the `controller` container.

Now the error is:

```
x509: certificate is valid for cf4b4945b471, docker, localhost, not dind
```

So the solution should be that adding `dind` as a trusted domain for TLS certificate.

**Comment by mapleeit** [comment]
Current temporary solution could be:

1. Add hostname for `dind` container: `hostname: docker`
2. Use `docker:2376` instead of `dind:2376`. `docker --tlsverify -H=tcp://docker:2376 --tlscacert=/certs/ca/cert.pem --tlscert=/certs/client/cert.pem --tlskey=/certs/client/key.pem version `

```yaml
version: "3.9"
services:
    controller:
        build: .
        ports:
            - 3001:3000
        volumes:
            - cert-volume:/certs
    dind:
        image: docker:20-dind
        privileged: true
        environment: 
            DOCKER_TLS_CERTDIR: /certs
        volumes: 
            - cert-volume:/certs
        hostname: docker

volumes: 
    cert-volume:
```
