### ISSUE TITLE
OOM 137 running DinD

### ISSUE THREAD

**Issue by jribmartins** [docker-library/docker#316]
Hello all,

I'm using the docker:18.09-dind and having some problems building images.
I got for some builds the 137 OOM error:

`The command '/bin/sh ... returned a non-zero code: 137`

It seems like a out of memory issue. Am I able to define more memory on this? Thanks

Im using following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dind-slave
  name: dind-slave
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dind-slave
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dind-slave
    spec:
      containers:
      - image: docker:18.09-dind
        imagePullPolicy: IfNotPresent
        name: docker
        resources:
          requests:
            cpu: 500m
            memory: 8192Mi
          limits:
            cpu: 8000m
            memory: 16384Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

```
