### ISSUE TITLE
Cannot read uid_map in dind-rootless unprivileged

### ISSUE THREAD

**Issue by czunker** [docker-library/docker#330]
I'm trying to run dind-rootless **without** `privileged`.

I'm aware, that the docs and different issues say, that the `privileged` flag is still needed to run dind-rootless.
But the [docs](https://docs.docker.com/engine/security/rootless/#rootless-docker-in-docker) also state, that it is only required to
> disabling seccomp, AppArmor, and mount masks.

So, I wanted to give it a try by changing these settings upfront for a Kubernetes deployment:
```
apiVersion: v1
kind: Pod
metadata:
  name: dind-rootless-unpriv
  annotations:
    container.apparmor.security.beta.kubernetes.io/dind: unconfined
spec:
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: Unconfined
  containers:
    - name: dind
      image: docker:20.10-dind-rootless
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      securityContext:
        privileged: false
        procMount: Unmasked
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL
          add:
            - SETGID
            - SETUID
```
This is based on:
Ubuntu 20.04
containerd 1.5.2-0ubuntu1~20.04.2
k0s 1.21.3
uidmap 1:4.8.1-1ubuntu5.20.04.1
k0s has the `--feature-gates=ProcMountType=true` set to make the `procMount: Unmasked` work.

But I get this error during startup of dind-rootless:
```
[rootlesskit:parent] error: failed to setup UID/GID map: newuidmap 35 [0 1000 1 1 100000 65536] failed: newuidmap: open of uid_map failed: Permission denied
: exit status 1
```

I came across this issue which mentions the same problem for img: https://github.com/genuinetools/img/issues/191

Adding the capability `SYS_ADMIN`, as mentioned in the above issue, didn't solve the problem. And this capability is actually not what I was aiming for.

And it is a different problem as mentioned in https://github.com/docker-library/docker/issues/296.
The write error can be fixed with the `SETGID`/`SETUID` capabilities.

The only other hint I could find is https://github.com/docker-library/docker/issues/151#issuecomment-483185972
There @AkihiroSuda states, that `privileged` is also needed to mount `sysfs`. Perhaps something is missing for this case?

I'm not certain whether this is really an issue, or works as designed. Reading the docs past the
> `--privileged` is required

I was curious to give it a try.
