### ISSUE TITLE
Persist docker Images through multiple docker:dind containers?

### ISSUE THREAD

**Issue by LQss11** [docker-library/docker#349]
I am to scale multiple **dind containers** using `docker-compose` command.

**docker-compose.yaml**
```yaml
version: '3.8'

networks:
  net:
    driver: bridge

volumes:
  dind-images:

services:
  # DinD Container Configuration
  agent:
    image: docker:dind
    volumes:
      - 'dind-images:/var/lib/docker/image'  # Persist docker images through dind containers
    privileged: true    
    tty: true
    networks:
      - net          
```
and I am running this compose file with:
```sh
docker-compose up -d --scale agent=4
```
I am mapping `/var/lib/docker/image` to a volume called `dind-images` through multiple dind containers the problem is whenever I try to run `docker image pull image_name` in one of them, then run `docker image ls` I only get the image name listed in the only dind container I used pull command on but won't show on other containers.

**WHEN I RESTART CONTAINERS WITH `docker-compose down|up` I CAN SEE IMAGES ON ALL OF THEM**

Am I missing something and would that affect the next runs?

>When I run `docker image pull image_name` on the other containers it takes only a second to pull (which means that it finds the image data) but when I run `docker image ls` it doesn't show the image).
>>I feel like there is other data I need to include in volumes but I don't know what exactly.

Pulling image on 1st dind container:
![Dind1](https://user-images.githubusercontent.com/49565791/149033384-7acb7fc8-b8a9-4917-9f1e-2a525788f8d8.PNG)

Pulling Image after downloading image from 1st dind container:
![Dind2](https://user-images.githubusercontent.com/49565791/149033362-1e8b1026-05d6-4d65-aedd-119cd23d8db8.PNG)
