### ISSUE TITLE
network bridge not found

### ISSUE THREAD

**Issue by wburgers** [docker-library/docker#400]
We have a Jenkins CI running with Kubernetes build executors.

In our Jenkins buildfile we can specify different nodes for different stages of a build.
One of the stages builds a docker image with the docker container.

Definition of the node:
```
- name: docker
    image: docker
    command:
    - cat
    resources:
      requests:
        memory: '256Mi'
      limits:
        memory: '512Mi'
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock-volume
```

definition of the stage:
```
stage('Build docker image') {
            when { anyOf { branch 'master'; branch "release/*"; branch 'develop' } }
            steps {
                container('docker') {
                    sh 'cp -R dist/application docker/'
                    dir('docker') {
                        withCredentials(...) {
                            sh 'echo $registry_password | docker login private-registry --username $registry_username --password-stdin'
                            sh 'docker build -t application .'

                            sh "docker tag application:latest private-registry/application:${TAG}"
                            sh 'docker push -a private-registry/application'
                            sh 'docker logout'
                        }
                    }
                }
            }
        }
```

With version 20 of the docker in docker image it works.
With version 23 of the docker in docker image it fails in building the docker image of our application.

The error is:
```
#9 [5/5] RUN ["chmod", "+x", "/docker-entrypoint.d/99-configure-variables.sh"]
#9 ERROR: executor failed running [chmod +x /docker-entrypoint.d/99-configure-variables.sh]: network bridge not found
------
 > [5/5] RUN ["chmod", "+x", "/docker-entrypoint.d/99-configure-variables.sh"]:
------
ERROR: failed to solve: executor failed running [chmod +x /docker-entrypoint.d/99-configure-variables.sh]: network bridge not found
```

Is there something wrong with our setup or is this a bug in version 23?
