### ISSUE TITLE
Unable to Provide my own certificates

### ISSUE THREAD

**Issue by tete17** [docker-library/docker#401]
This is "_sort of a regression due to a patch_" release but with a lot of caveats.

My "issue" was introduced with https://github.com/docker-library/docker/commit/38e13c81eb5cb5b10d4477467547b0823d877720

My use case for dind images is in the context of the Gitlab CI Runners in k8s environments. I want to make use of docker when building our images and for that I use dind as a service image.
```yaml
build:
  services:
    - name: docker:20.10-dind
      alias: docker
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker -D login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
```

This alone leads to problems since the time it takes for the dind container to spin up a cert infrastructure is not insignificant and since the side container in k8s is launched at the same time we saw many times that the build container tried to contact the daemon before it open its port.

To fix this I tried setting my own PKI infra using cert-manager and I inject the secret into the container as a read-only volume.
```toml
[[runners]]
        [runners.kubernetes]
          privileged = true

        ## Needed for k8s dind to work
        ## ref: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-in-docker-with-tls-enabled-in-kubernetes
        [[runners.kubernetes.volumes.secret]]
          name = "dind-client-certs"
          mount_path = "/certs/client"
          read_only = true
          [runners.kubernetes.volumes.secret.items]
            "ca.crt" = "ca.pem"
            "tls.crt" = "cert.pem"
            "tls.key" = "key.pem"

        [[runners.kubernetes.volumes.secret]]
          name = "dind-server-certs"
          mount_path = "/certs/server"
          read_only = true
          [runners.kubernetes.volumes.secret.items]
            "ca.crt" = "ca.pem"
            "tls.crt" = "cert.pem"
            "tls.key" = "key.pem"
``` 

This worked fine for now since the entrypoint would silently error out and then launch the ssl setup anyway. Not anymore. For now we reverted to `docker:20.10.22-dind` and we can work with it, but I wonder if you guys would be open to PR adding a variable like `DOCKER_DONT_CREATE_TLS` that would disable the constant generation of these certs?
