### ISSUE TITLE
after upgrade from v26 to v27 dind fails to start: Unexpected error in sigtimedwait: 'Function not implemented'

### ISSUE THREAD

**Issue by mrclrchtr** [docker-library/docker#503]
I tried to upgrade from v26 to v27.

I want to use docker dind in a github actions runner scale set with the following config:

```yaml
image: docker:27.0.2-dind
name: dind
securityContext:
  privileged: true
env:
  - name: DOCKER_GROUP_GID
    value: "123"
resources:
  requests:
    cpu: 300m
    memory: 500Mi
  limits:
    cpu: 300m
    memory: 500Mi
args:
  - dockerd
  - --host=unix:///var/run/docker.sock
  - --group=$(DOCKER_GROUP_GID)
```

This ist the complete log, I can get:
```log
cat: can't open '/proc/net/arp_tables_names': No such file or directory
iptables v1.8.10 (nf_tables)
[FATAL tini (1)] Unexpected error in sigtimedwait: 'Function not implemented'
```

The underlaying OS is Talos v1.7.4

Do you have any idea, whats happening?
