### ISSUE TITLE
MAC address changed with the update

### ISSUE THREAD

**Issue by LordMilutin** [docker-library/docker#518]
Hello. 
I have a docker-compose file that has fixed MAC address. 
Everything worked flawlessly until recently which I suspect is the new docker update. 

Now, when I redeploy the container (docker-compose down && docker-compose up), my fixed MAC address is changed. 

I can still see the old one in one part of docker inspect command, but under Networks, it is another one. This used to be the fixed address, however that is not the case anymore. 

Is there anything that can be done to preserve that fixed address again under Network, since our licences are based on MAC addresses.

My docker-compse:

```                                                                            
services:
  serx:
    image: registry.my.ap/app:release
    container_name: serx
    restart: always
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 4G
    mac_address: 00:e0:84:35:d0:e8
```
