### ISSUE TITLE
init Additional property init is not allowed

### ISSUE THREAD

**Issue by acca301** [docker-library/docker#78]
Trying to deploy a stack with Docker 17.06.2-ce

A service is having 'init:' property set:
```yml
version: "3.1"
services:
  dummy:
    image: hello-world
    init: true
```
Getting an error:
```
$ docker stack deploy -c dummy.yml dummy
init Additional property init is not allowed
```

The 'init:' option had been introduced in version 2.2 of 'docker-compose' format. Any clue would be greatly appreciated.
